# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@importFrom Rcpp evalCpp
#'@useDynLib BFFscreening, .registration=TRUE
NULL

#'@export
HOLP_screening <- function(x, y, theta = 1e-3) {
    .Call(`_BFFscreening_HOLP_screening`, x, y, theta)
}

#'@export
fast_data_gen <- function(n, p, R2, beta_nonzero) {
    .Call(`_BFFscreening_fast_data_gen`, n, p, R2, beta_nonzero)
}

#'@export
BFF_screening_local_spatial <- function(x, y, coords, neighbors, num_neighbors, rho, theta = 1e-3) {
    .Call(`_BFFscreening_BFF_screening_local_spatial`, x, y, coords, neighbors, num_neighbors, rho, theta)
}

#'@export
fast_read_imgs_mask <- function(imgfiles, maskfile, verbose = 100L) {
    .Call(`_BFFscreening_fast_read_imgs_mask`, imgfiles, maskfile, verbose)
}

